"""empty message

Revision ID: 025f5670f8fb
Revises: 27c2b83947de
Create Date: 2020-05-10 20:17:05.136873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '025f5670f8fb'
down_revision = '27c2b83947de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_column('users', 'is_staff')
    op.drop_column('users', 'img_link')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'human_token')
    op.drop_column('users', 'date_join')
    op.drop_column('users', 'zip_code')
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('users', sa.Column('zip_code', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('users', sa.Column('date_join', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('human_token', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('users', sa.Column('display_name', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('img_link', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('users', sa.Column('is_staff', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
