"""empty message

Revision ID: 0bb79b1cfe05
Revises: a93d0332ed46
Create Date: 2020-04-04 23:25:22.844271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb79b1cfe05'
down_revision = 'a93d0332ed46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roles_description', table_name='roles')
    op.create_index(op.f('ix_roles_description'), 'roles', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_description'), table_name='roles')
    op.create_index('ix_roles_description', 'roles', ['description'], unique=True)
    # ### end Alembic commands ###
