"""empty message

Revision ID: 13b8a71b4249
Revises: c3fe8aac5f84
Create Date: 2020-05-10 16:58:04.876917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13b8a71b4249'
down_revision = 'c3fe8aac5f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'role_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               autoincrement=True)
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['role_id'])
    op.drop_column('users', 'is_staff')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_staff', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.alter_column('roles', 'role_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               autoincrement=True)
    # ### end Alembic commands ###
