"""empty message

Revision ID: 30a836eefdbd
Revises: da86f8f30f3b
Create Date: 2020-04-19 19:22:51.788468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30a836eefdbd'
down_revision = 'da86f8f30f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('lobaction', sa.String(length=50), nullable=True))
    op.drop_column('users', 'sex')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sex', mysql.VARCHAR(length=6), nullable=True))
    op.drop_column('survey_responses', 'lobaction')
    # ### end Alembic commands ###
