"""empty message

Revision ID: 33c659783e10
Revises: 6f2b6c00f511
Create Date: 2020-04-25 18:58:39.299183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33c659783e10'
down_revision = '6f2b6c00f511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('survey_responses', sa.Column('lon', sa.Float(), nullable=True))
    op.drop_column('users', 'sticky_lat')
    op.drop_column('users', 'sticky_lon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sticky_lon', mysql.FLOAT(), nullable=True))
    op.add_column('users', sa.Column('sticky_lat', mysql.FLOAT(), nullable=True))
    op.drop_column('survey_responses', 'lon')
    op.drop_column('survey_responses', 'lat')
    # ### end Alembic commands ###
