"""empty message

Revision ID: 3c276f03bde2
Revises: e9193d907c53
Create Date: 2020-04-18 20:38:52.535889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c276f03bde2'
down_revision = 'e9193d907c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_responses',
    sa.Column('survey_response_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('self_test_result', sa.String(length=50), nullable=True),
    sa.Column('self_test_date', sa.DateTime(), nullable=True),
    sa.Column('household_test_result', sa.String(length=50), nullable=True),
    sa.Column('household_test_date', sa.DateTime(), nullable=True),
    sa.Column('thermometer_temp', sa.Float(), nullable=True),
    sa.Column('temp_guess', sa.String(length=50), nullable=True),
    sa.Column('has_symptom_no_smell_taste', sa.Boolean(), nullable=True),
    sa.Column('has_symptom_extreme_fatigue', sa.Boolean(), nullable=True),
    sa.Column('has_symptom_wet_cough', sa.Boolean(), nullable=True),
    sa.Column('has_symptom_dry_cough', sa.Boolean(), nullable=True),
    sa.Column('has_symptom_abdominal_pain', sa.Boolean(), nullable=True),
    sa.Column('has_symptom_diarrhea', sa.Boolean(), nullable=True),
    sa.Column('has_symptom_sore_throat', sa.Boolean(), nullable=True),
    sa.Column('has_symptom_chills', sa.Boolean(), nullable=True),
    sa.Column('has_symptom_nausea_vomiting', sa.Boolean(), nullable=True),
    sa.Column('has_symptom_pressure_chest', sa.Boolean(), nullable=True),
    sa.Column('has_symptom_pink_eye', sa.Boolean(), nullable=True),
    sa.Column('has_symptom_other', sa.Boolean(), nullable=True),
    sa.Column('datetime_submitted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('survey_response_id'),
    sa.UniqueConstraint('survey_response_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_responses')
    # ### end Alembic commands ###
