"""empty message

Revision ID: 4cb4de8935b7
Revises: 63af241c38d1
Create Date: 2020-04-05 12:44:26.136028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4cb4de8935b7'
down_revision = '63af241c38d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(length=50), nullable=True))
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('first_name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
