"""empty message

Revision ID: 4d94dfdc04c1
Revises: 13b8a71b4249
Create Date: 2020-05-10 17:00:45.026362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d94dfdc04c1'
down_revision = '13b8a71b4249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roles_description', table_name='roles')
    op.drop_index('ix_roles_name', table_name='roles')
    op.drop_index('role_id', table_name='roles')
    op.drop_table('roles')
    op.drop_column('users', 'is_staff')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_staff', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_table('roles',
    sa.Column('role_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('role_id', 'roles', ['role_id'], unique=True)
    op.create_index('ix_roles_name', 'roles', ['name'], unique=False)
    op.create_index('ix_roles_description', 'roles', ['description'], unique=False)
    # ### end Alembic commands ###
