"""empty message

Revision ID: 5ec40ce46095
Revises: 5af7ff828b91
Create Date: 2020-04-11 15:00:41.560975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec40ce46095'
down_revision = '5af7ff828b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('location_id', sa.String(length=50), nullable=True),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.Column('lat', sa.Integer(), nullable=True),
    sa.Column('lon', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('location_id'),
    sa.UniqueConstraint('location_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    # ### end Alembic commands ###
