"""empty message

Revision ID: 63af241c38d1
Revises: 0bb79b1cfe05
Create Date: 2020-04-04 23:26:28.524729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63af241c38d1'
down_revision = '0bb79b1cfe05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'roles', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='unique')
    # ### end Alembic commands ###
