"""empty message

Revision ID: 6a235d61ba98
Revises: 703a35d3eea3
Create Date: 2020-04-19 20:10:17.313935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a235d61ba98'
down_revision = '703a35d3eea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('feeling_well', sa.String(length=50), nullable=True))
    op.add_column('survey_responses', sa.Column('household_tested_date', sa.DateTime(), nullable=True))
    op.add_column('survey_responses', sa.Column('self_tested_date', sa.DateTime(), nullable=True))
    op.drop_column('survey_responses', 'household_test_date')
    op.drop_column('survey_responses', 'self_test_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('self_test_date', mysql.DATETIME(), nullable=True))
    op.add_column('survey_responses', sa.Column('household_test_date', mysql.DATETIME(), nullable=True))
    op.drop_column('survey_responses', 'self_tested_date')
    op.drop_column('survey_responses', 'household_tested_date')
    op.drop_column('survey_responses', 'feeling_well')
    # ### end Alembic commands ###
