"""empty message

Revision ID: 6f2b6c00f511
Revises: 542943cf243e
Create Date: 2020-04-22 19:28:22.484000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f2b6c00f511'
down_revision = '542943cf243e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.String(length=250), nullable=True))
    op.add_column('users', sa.Column('human_token', sa.String(length=250), nullable=True))
    op.alter_column('users', 'img_link',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=True)
    op.drop_column('users', 'sex')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sex', mysql.VARCHAR(length=6), nullable=True))
    op.alter_column('users', 'img_link',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('users', 'human_token')
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###
