"""empty message

Revision ID: 7d85c59fe5ee
Revises: 18a5794e743f
Create Date: 2020-04-12 00:07:16.440794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d85c59fe5ee'
down_revision = '18a5794e743f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_join', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_join')
    # ### end Alembic commands ###
