"""empty message

Revision ID: 86633417e9e9
Revises: f3e4da3a3639
Create Date: 2020-05-10 16:50:34.064843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86633417e9e9'
down_revision = 'f3e4da3a3639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('location_id', table_name='location')
    op.drop_table('location')
    op.drop_index('temperature_id', table_name='temperature')
    op.drop_table('temperature')
    op.drop_index('medical_history_id', table_name='medical_history')
    op.drop_table('medical_history')
    op.drop_index('sentiment_id', table_name='sentiment')
    op.drop_table('sentiment')
    op.drop_table('survey_metadata')
    op.alter_column('roles', 'role_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               autoincrement=True)
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['role_id'])
    op.drop_column('users', 'is_staff')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_staff', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.alter_column('roles', 'role_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               autoincrement=True)
    op.create_table('survey_metadata',
    sa.Column('survey_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('datetime_submitted', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='survey_metadata_ibfk_1'),
    sa.PrimaryKeyConstraint('survey_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sentiment',
    sa.Column('sentiment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('survey_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sentiment', mysql.VARCHAR(length=250), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey_metadata.survey_id'], name='sentiment_ibfk_1'),
    sa.PrimaryKeyConstraint('sentiment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('sentiment_id', 'sentiment', ['sentiment_id'], unique=True)
    op.create_table('medical_history',
    sa.Column('medical_history_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('survey_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('high_blood_pressure', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('asthma', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('copd_emphysema', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('chronic_kidney_disease', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('liver_disease', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('cancer', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('diabetes', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('cardiovascular_disease', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('hiv_aids', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('bmi_over_40', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`asthma` in (0,1))', name='medical_history_chk_2'),
    sa.CheckConstraint('(`bmi_over_40` in (0,1))', name='medical_history_chk_10'),
    sa.CheckConstraint('(`cancer` in (0,1))', name='medical_history_chk_6'),
    sa.CheckConstraint('(`cardiovascular_disease` in (0,1))', name='medical_history_chk_8'),
    sa.CheckConstraint('(`chronic_kidney_disease` in (0,1))', name='medical_history_chk_4'),
    sa.CheckConstraint('(`copd_emphysema` in (0,1))', name='medical_history_chk_3'),
    sa.CheckConstraint('(`diabetes` in (0,1))', name='medical_history_chk_7'),
    sa.CheckConstraint('(`high_blood_pressure` in (0,1))', name='medical_history_chk_1'),
    sa.CheckConstraint('(`hiv_aids` in (0,1))', name='medical_history_chk_9'),
    sa.CheckConstraint('(`liver_disease` in (0,1))', name='medical_history_chk_5'),
    sa.ForeignKeyConstraint(['survey_id'], ['survey_metadata.survey_id'], name='medical_history_ibfk_1'),
    sa.PrimaryKeyConstraint('medical_history_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('medical_history_id', 'medical_history', ['medical_history_id'], unique=True)
    op.create_table('temperature',
    sa.Column('temperature_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('survey_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('therm_temp', mysql.FLOAT(), nullable=True),
    sa.Column('temp_guess', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey_metadata.survey_id'], name='temperature_ibfk_1'),
    sa.PrimaryKeyConstraint('temperature_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('temperature_id', 'temperature', ['temperature_id'], unique=True)
    op.create_table('location',
    sa.Column('location_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('survey_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latitude', mysql.FLOAT(), nullable=True),
    sa.Column('longitude', mysql.FLOAT(), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('zip_code', mysql.VARCHAR(length=25), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey_metadata.survey_id'], name='location_ibfk_1'),
    sa.PrimaryKeyConstraint('location_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('location_id', 'location', ['location_id'], unique=True)
    # ### end Alembic commands ###
