"""empty message

Revision ID: b899311a97ce
Revises: a985c9cb946a
Create Date: 2020-04-12 10:40:26.645975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b899311a97ce'
down_revision = 'a985c9cb946a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_results',
    sa.Column('record_id', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('positive', sa.Integer(), nullable=True),
    sa.Column('positiveScore', sa.Integer(), nullable=True),
    sa.Column('negativeScore', sa.Integer(), nullable=True),
    sa.Column('negativeRegularScore', sa.Integer(), nullable=True),
    sa.Column('commercialScore', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('negative', sa.Integer(), nullable=True),
    sa.Column('pending', sa.Integer(), nullable=True),
    sa.Column('hospitalizedCurrently', sa.Integer(), nullable=True),
    sa.Column('hospitalizedCumulative', sa.Integer(), nullable=True),
    sa.Column('inIcuCurrently', sa.Integer(), nullable=True),
    sa.Column('inIcuCumulative', sa.Integer(), nullable=True),
    sa.Column('onVentilatorCurrently', sa.Integer(), nullable=True),
    sa.Column('onVentilatorCumulative', sa.Integer(), nullable=True),
    sa.Column('recovered', sa.Integer(), nullable=True),
    sa.Column('lastUpdateEt', sa.String(length=50), nullable=True),
    sa.Column('checkTimeEt', sa.String(length=50), nullable=True),
    sa.Column('death', sa.Integer(), nullable=True),
    sa.Column('hospitalized', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('totalTestResults', sa.Integer(), nullable=True),
    sa.Column('posNeg', sa.Integer(), nullable=True),
    sa.Column('fips', sa.String(length=50), nullable=True),
    sa.Column('dateModified', sa.DateTime(), nullable=True),
    sa.Column('dateChecked', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=100), nullable=True),
    sa.Column('hash', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('record_id')
    )
    op.create_table('location',
    sa.Column('location_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('location_id'),
    sa.UniqueConstraint('location_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    op.drop_table('state_results')
    # ### end Alembic commands ###
