"""empty message

Revision ID: c66ee806abf0
Revises: 56d19e0db7f5
Create Date: 2020-04-21 21:24:27.119210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66ee806abf0'
down_revision = '56d19e0db7f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('sex', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sex')
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###
