"""empty message

Revision ID: d34b429440da
Revises: 15dafd02b1b1
Create Date: 2020-05-10 20:14:36.633626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd34b429440da'
down_revision = '15dafd02b1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('survey_responses', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_column('survey_responses', 'history_asthma')
    op.drop_column('survey_responses', 'has_symptom_abdominal_pain')
    op.drop_column('survey_responses', 'has_symptom_dry_cough')
    op.drop_column('survey_responses', 'has_symptom_sore_throat')
    op.drop_column('survey_responses', 'has_symptom_nausea_vomiting')
    op.drop_column('survey_responses', 'has_symptom_no_smell_taste')
    op.drop_column('survey_responses', 'has_symptom_other')
    op.drop_column('survey_responses', 'history_liver_disease')
    op.drop_column('survey_responses', 'has_symptom_pink_eye')
    op.drop_column('survey_responses', 'has_symptom_extreme_fatigue')
    op.drop_column('survey_responses', 'history_cancer')
    op.drop_column('survey_responses', 'history_high_blood_pressure')
    op.drop_column('survey_responses', 'history_bmi_over_40')
    op.drop_column('survey_responses', 'history_hiv_aids')
    op.drop_column('survey_responses', 'has_symptom_pressure_chest')
    op.drop_column('survey_responses', 'has_symptom_chills')
    op.drop_column('survey_responses', 'feeling_well')
    op.drop_column('survey_responses', 'history_copd_emphysema')
    op.drop_column('survey_responses', 'history_cardiovascular_disease')
    op.drop_column('survey_responses', 'has_symptom_diarrhea')
    op.drop_column('survey_responses', 'history_diabetes')
    op.drop_column('survey_responses', 'has_symptom_wet_cough')
    op.drop_column('survey_responses', 'history_chronic_kidney_disease')
    op.drop_column('survey_responses', 'datetime_submitted')
    op.add_column('users', sa.Column('date_birth', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('firebase_id', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('sex', sa.String(length=2), nullable=True))
    op.alter_column('users', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               autoincrement=True)
    op.create_unique_constraint(None, 'users', ['firebase_id'])
    op.drop_column('users', 'img_link')
    op.drop_column('users', 'access_token')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'zip_code')
    op.drop_column('users', 'email')
    op.drop_column('users', 'date_join')
    op.drop_column('users', 'human_token')
    op.drop_column('users', 'is_staff')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_staff', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('human_token', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('users', sa.Column('date_join', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('zip_code', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('users', sa.Column('display_name', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('access_token', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('users', sa.Column('img_link', mysql.VARCHAR(length=250), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               autoincrement=True)
    op.drop_column('users', 'sex')
    op.drop_column('users', 'firebase_id')
    op.drop_column('users', 'date_birth')
    op.add_column('survey_responses', sa.Column('datetime_submitted', mysql.DATETIME(), nullable=True))
    op.add_column('survey_responses', sa.Column('history_chronic_kidney_disease', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('has_symptom_wet_cough', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('history_diabetes', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('has_symptom_diarrhea', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('history_cardiovascular_disease', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('history_copd_emphysema', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('feeling_well', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('survey_responses', sa.Column('has_symptom_chills', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('has_symptom_pressure_chest', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('history_hiv_aids', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('history_bmi_over_40', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('history_high_blood_pressure', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('history_cancer', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('has_symptom_extreme_fatigue', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('has_symptom_pink_eye', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('history_liver_disease', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('has_symptom_other', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('has_symptom_no_smell_taste', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('has_symptom_nausea_vomiting', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('has_symptom_sore_throat', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('has_symptom_dry_cough', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('has_symptom_abdominal_pain', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('history_asthma', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.alter_column('survey_responses', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
