"""empty message

Revision ID: dee157fbd76d
Revises: 33c659783e10
Create Date: 2020-04-25 19:09:05.427094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dee157fbd76d'
down_revision = '33c659783e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('survey_responses', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_column('survey_responses', 'location')
    op.drop_column('users', 'sticky_lon')
    op.drop_column('users', 'sticky_lat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sticky_lat', mysql.FLOAT(), nullable=True))
    op.add_column('users', sa.Column('sticky_lon', mysql.FLOAT(), nullable=True))
    op.add_column('survey_responses', sa.Column('location', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('survey_responses', 'longitude')
    op.drop_column('survey_responses', 'latitude')
    # ### end Alembic commands ###
