"""empty message

Revision ID: e558712e9d93
Revises: 7d85c59fe5ee
Create Date: 2020-04-12 00:51:36.565611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e558712e9d93'
down_revision = '7d85c59fe5ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('img_link', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('sticky_lat', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('sticky_lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sticky_lon')
    op.drop_column('users', 'sticky_lat')
    op.drop_column('users', 'img_link')
    # ### end Alembic commands ###
