"""empty message

Revision ID: ed02b69c4934
Revises: b899311a97ce
Create Date: 2020-04-12 13:25:13.703744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed02b69c4934'
down_revision = 'b899311a97ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('state_results', 'dateChecked',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('state_results', 'dateModified',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('users', 'birth',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birth',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('state_results', 'dateModified',
               existing_type=sa.String(length=50),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('state_results', 'dateChecked',
               existing_type=sa.String(length=50),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
