"""empty message

Revision ID: eebc6b4d670e
Revises: e558712e9d93
Create Date: 2020-04-12 09:53:07.918376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eebc6b4d670e'
down_revision = 'e558712e9d93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('location_id', table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('location_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('lat', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lon', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='location_ibfk_1'),
    sa.PrimaryKeyConstraint('location_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('location_id', 'location', ['location_id'], unique=True)
    # ### end Alembic commands ###
