"""empty message

Revision ID: f5b9583d9d2f
Revises: 86633417e9e9
Create Date: 2020-05-10 16:52:10.124879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5b9583d9d2f'
down_revision = '86633417e9e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'role_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               autoincrement=True)
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['role_id'])
    op.drop_column('users', 'is_staff')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_staff', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.alter_column('roles', 'role_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               autoincrement=True)
    # ### end Alembic commands ###
